### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by hxm2954** [RUCKBReasoning/RESDSQL#10]
When I run the requirements file.

I am getting this error.
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for jarowinkler
Failed to build rapidfuzz tokenizers jarowinkler
ERROR: Could not build wheels for rapidfuzz, tokenizers, jarowinkler, which is required to install pyproject.toml-based projects

can you please tell me how do i install this which are on requirement list?

**Comment by lihaoyang-ruc** [comment]
It seems to be a development environment issue.

This project is implemented on Ubuntu 20.04.2, using Anaconda 4.9.2 (`Anaconda3-2020.11-Linux-x86_64.sh` in [anaconda repo](https://repo.anaconda.com/archive/)).

Maybe you can Google the error log and find something useful.

**Comment by lihaoyang-ruc** [comment]
This question is closed due to inactivity. If you have further questions, please feel free to open it again or create a new question.
