### ISSUE TITLE
对中文的支持

### ISSUE THREAD

**Issue by caseylai** [RUCKBReasoning/RESDSQL#11]
目前看示例代码中使用的模型和数据集均是来自于英文，自测了一下也确实对中文的支持还不好。想请问一下，如果想移植到中文环境使用，是需要把训练使用的RoBERTa模型、T5模型、训练数据集都换成中文的是吧？大概在网上找了一下，也找了几个对应的模型和数据集，请问下研发团队之前做过类似的尝试吗，有没有遇到什么困难或者障碍？

我找到的几个中文模型及数据集资源：
https://github.com/brightmart/roberta_zh
https://github.com/SunnyGJing/t5-pegasus-chinese
https://taolusi.github.io/CSpider-explorer/

**Comment by lihaoyang-ruc** [comment]
你好，我们在 #7 中对类似问题进行过讨论。

“把训练使用的RoBERTa模型、T5模型、训练数据集都换成中文”的想法是正确的，但我们团队还没有尝试过。我们推荐您使用Huggingface模型库中提供的多语言（起码支持中文和英文）RoBERTa和T5进行训练。

如果遇到任何问题，请随时与我联系 :)

**Comment by lihaoyang-ruc** [comment]
@caseylai 你好，我们支持了CSpider（中文Text-to-SQL数据集）上的训练和评估，欢迎下载使用。
