### ISSUE TITLE
checkpoint下载失败

### ISSUE THREAD

**Issue by hexiaoting** [RUCKBReasoning/RESDSQL#13]
您好，请问一下 T5 checkpoints 怎么下载？表格里的google drive的两个link下载下来是两个文件夹：
text2sql_schema_item_classifier
text2natsql_schema_item_classifier

没有看到text2natsql-t5-3b，text2natsql-t5-base等目录，请问一下这些是怎么出来的？是我下载的不对吗？
<img width="802" alt="image" src="https://user-images.githubusercontent.com/7898329/231633919-3b20e31e-2ecf-4587-b393-7edc5d9325ee.png">

**Comment by lihaoyang-ruc** [comment]
你好！
我们在Step1: Prepare Checkpoints的第一句有提到：“First, you should download T5 checkpoints from **the table shown above**. ”。因此，text2sql-t5和text2natsql-t5在这张表列出的链接下载：
<img width="855" alt="image" src="https://user-images.githubusercontent.com/45526716/231634778-2710f460-8c5a-4dd9-a592-759d4feaed07.png">

**Comment by hexiaoting** [comment]
好，谢谢
