### ISSUE TITLE
The repository does not have a license

### ISSUE THREAD

**Issue by vermouthmjl** [RUCKBReasoning/RESDSQL#14]
Thank you so much for your wonderful work.

Currently, the repository does not have a license. According to the [github documentation](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository)

> You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work. If you're creating an open source project, we strongly encourage you to include an open source license.

Do you think you could add an open source license to the repository, so that other people are legally allowed to reproduce, distribute, or create derivative works from it?

More discussion on this matter
- https://opensource.stackexchange.com/questions/1150/is-my-code-floss-just-because-it-is-published-it-on-github
- https://opensource.stackexchange.com/questions/1720/what-can-i-assume-if-a-publicly-published-project-has-no-license

**Comment by lihaoyang-ruc** [comment]
Hello! Thank you very much for your constructive suggestion, we will add an open-source license so that everyone can feel free to use this repository.

**Comment by lihaoyang-ruc** [comment]
We added the MIT license. Thanks again!
