### ISSUE TITLE
The SQL skeleton is a too easy objective

### ISSUE THREAD

**Issue by wikty** [RUCKBReasoning/RESDSQL#15]
I have trained 10 epochs in Spider with seq-to-seq framework model. If the target objective just as original SQL, the results is about 60%+. But when switching to skeleton+SQL, the performance is so bad. 

After manual check, I found that the model inference result only contains the skeleton, and there is no SQL at all. Have you ever encountered this problem?

**Comment by lihaoyang-ruc** [comment]
Hi,
Unfortunately, I have never encountered this problem. The output of the decoder is a concatenation of the SQL skeleton and the original SQL query, which is split by a delimiter `|`. You can check your dataset to make sure the output sequence is of this form.

**Comment by wikty** [comment]
That's very weird. I did add the delimiter. I will continue to debug.

By the way, have you trained 128 epochs on the Spider dataset, why do you train so many steps?

**Comment by lihaoyang-ruc** [comment]
We should ensure that the model converges "perfectly" on the training set. Therefore, we set the epochs to 128 :)
