### ISSUE TITLE
inference scripts error

### ISSUE THREAD

**Issue by fz5400** [RUCKBReasoning/RESDSQL#21]
你好， 我在尝试使用模型推理的时候出现了一些问题：
我使用的模型是RESDSQL-base, 在前期工作准备完成后使用了`sh scripts/inference/infer_text2sql.sh base spider` 指令进行推理，出现了如下错误：

> Traceback (most recent call last):
>   File "schema_item_classifier.py", line 463, in <module>
>     total_table_pred_probs, total_column_pred_probs = _test(opt)
>   File "schema_item_classifier.py", line 428, in _test
>     batch_column_number_in_each_table
>   File "/root/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/mnt/data/_tt_/RESDSQL/utils/classifier_model.py", line 191, in forward
>     batch_column_number_in_each_table
>   File "/mnt/data/_tt_/RESDSQL/utils/classifier_model.py", line 134, in table_column_cls
>     output_t, (hidden_state_t, cell_state_t) = self.table_name_bilstm(table_name_embeddings)
>   File "/root/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/root/miniconda3/lib/python3.7/site-packages/torch/nn/modules/rnn.py", line 689, in forward
>     self.check_forward_args(input, hx, batch_sizes)
>   File "/root/miniconda3/lib/python3.7/site-packages/torch/nn/modules/rnn.py", line 632, in check_forward_args
>     self.check_input(input, batch_sizes)
>   File "/root/miniconda3/lib/python3.7/site-packages/torch/nn/modules/rnn.py", line 203, in check_input
>     expected_input_dim, input.dim()))
> RuntimeError: input must have 3 dimensions, got 2

于是我在`./untils/classifier_model.py`的line 134 加入：
> print(table_name_embeddings.size(),table_name_embeddings)
> table_name_embeddings = table_name_embeddings.unsqueeze(0)
> print(table_name_embeddings.size(),table_name_embeddings)

后续报错：

> torch.Size([1, 1024]) tensor([[-0.3795, -0.9529,  0.9007,  ..., -0.6501, -2.1801,  0.9587]],
>        device='cuda:0')
> torch.Size([1, 1, 1024]) tensor([[[-0.3795, -0.9529,  0.9007,  ..., -0.6501, -2.1801,  0.9587]]],
>        device='cuda:0')
> torch.Size([1, 1024]) tensor([[-0.7597, -0.5682, -0.4270,  ...,  0.3219,  1.5417,  0.3518]],
>        device='cuda:0')
> torch.Size([1, 1, 1024]) tensor([[[-0.7597, -0.5682, -0.4270,  ...,  0.3219,  1.5417,  0.3518]]],
>        device='cuda:0')
> torch.Size([1, 1024]) tensor([[-0.4921, -1.1286,  0.9307,  ..., -0.5373, -2.0887,  0.9216]],
>        device='cuda:0')
> torch.Size([1, 1, 1024]) tensor([[[-0.4921, -1.1286,  0.9307,  ..., -0.5373, -2.0887,  0.9216]]],
>        device='cuda:0')
> torch.Size([3, 1024]) tensor([[-0.5896, -1.3575,  1.1120,  ..., -0.6104, -1.9414,  0.6679],
>         [-0.6831, -1.3711,  1.1447,  ..., -0.5117, -2.0709,  0.8956],
>         [-0.6337, -1.3548,  1.2228,  ..., -0.4896, -2.0505,  0.8417]],
>        device='cuda:0')
> torch.Size([1, 3, 1024]) tensor([[[-0.5896, -1.3575,  1.1120,  ..., -0.6104, -1.9414,  0.6679],
>          [-0.6831, -1.3711,  1.1447,  ..., -0.5117, -2.0709,  0.8956],
>          [-0.6337, -1.3548,  1.2228,  ..., -0.4896, -2.0505,  0.8417]]],
>        device='cuda:0')
>   0%|                                                                                                     | 0/33 [00:01<?, ?it/s]
> Traceback (most recent call last):
>   File "schema_item_classifier.py", line 462, in <module>
>     total_table_pred_probs, total_column_pred_probs = _test(opt)
>   File "schema_item_classifier.py", line 427, in _test
>     batch_column_number_in_each_table
>   File "/root/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/mnt/data/_tt_/RESDSQL/utils/classifier_model.py", line 194, in forward
>     batch_column_number_in_each_table
>   File "/mnt/data/_tt_/RESDSQL/utils/classifier_model.py", line 138, in table_column_cls
>     table_name_embedding = hidden_state_t[-2:, :].view(1, 1024)
> RuntimeError: shape '[1, 1024]' is invalid for input of size 3072

对于修改这些错误，需要一些帮助。感谢🙏

**Comment by lihaoyang-ruc** [comment]
你现在使用的是什么操作系统呢？Windows？Linux？如果是Windows，我建议你切换到Linux运行本项目。除此之外，对同一个函数，不同版本的pytorch在具体实现时可能会不同，因此请确保你的Python环境（特别是模块的版本）是按照我们的推荐正确配置的。

**Comment by fz5400** [comment]
感谢感谢，问题解决了，我使用的是Linux系统，之前使用的虚拟环境是python 3.7.9，现在将环境调整为python 3.8.5就可以顺利跑通了。确实应该是版本的冲突导致的问题。
