### ISSUE TITLE
CSpider上加不加NatSQL的性能差异有多大？

### ISSUE THREAD

**Issue by exitxingling** [RUCKBReasoning/RESDSQL#26]
想请问一下在Cspider上，mT5-base模型不加NatSQL的性能比加了NatSQL的差几个点呀？

**Comment by lihaoyang-ruc** [comment]
会差挺多，但具体差多少我不记得了，你可以参考下这个人的结果：https://github.com/RUCKBReasoning/RESDSQL/issues/12#issuecomment-1571164073
当然，你也可以自己在24G的显卡上训练一遍mT5-base，应该花不了太长时间。
