### ISSUE TITLE
在解码的时候，做了哪些后处理

### ISSUE THREAD

**Issue by 694344851** [RUCKBReasoning/RESDSQL#29]
我想知道在解码的时候做了哪些后处理，有具体的步骤么
            pred_natsql = fix_fatal_errors_in_natsql(pred_natsql, batch_tc_original[batch_id])
            if old_pred_natsql != pred_natsql:
                print("Before fix:", old_pred_natsql)
                print("After fix:", pred_natsql)
                print("---------------")
            pred_sql = natsql_to_sql(pred_natsql, db_id, db_file_path, table_dict[db_id]).strip()
因为我发现在不进行后处理，直接解码的效果很差

**Comment by lihaoyang-ruc** [comment]
text2natsql这边主要应用了两个后处理步骤：
一个是修复生成的natsql中存在的致命错误。
```
pred_natsql = fix_fatal_errors_in_natsql(pred_natsql, batch_tc_original[batch_id])
```
具体来说，我发现在极少数情况下，T5生成的sql会出现数据库中不存在的表名、列名，但是这些不存在的表名和列名能在数据库中能找到非常类似的表/列（举个例子，模型有时候会生成car_name表，但在数据库中的表名其实是car_names），因此我写了一个基于字符串匹配的修复函数来试图缓解这个问题。要注意的是，这个步骤不能保证修复后的natsql是完全没有问题的。

另一个就是将模型生成的natsql翻译回sql，因为natsql只是sql的一个中间表示。
```
pred_sql = natsql_to_sql(pred_natsql, db_id, db_file_path, table_dict[db_id]).strip()
```

**Comment by ManchesterWuer** [comment]
@lihaoyang-ruc natsql翻译成sql，有损失吗？我看他们的paper，貌似准确率>90%。

**Comment by lihaoyang-ruc** [comment]
有损失的，不能完全保证natsql翻译成正确的sql，但由于natsql相比于sql更简单，因此模型会学的更好，这是一个trade-off。

**Comment by 694344851** [comment]
请问一下，这个natsql具体做了一个怎么样的事情，可以具体一个例子么，论文看了，但是没有特别明白
