### ISSUE TITLE
这text2sql.py阶段所有的验证集都出现["sql placeholder"]是什么原因

### ISSUE THREAD

**Issue by 694344851** [RUCKBReasoning/RESDSQL#3]
sql placeholder
near "sql": syntax error
sql placeholder
near "sql": syntax error
sql placeholder
near "sql": syntax error
sql placeholder
near "sql": syntax error
sql placeholder
near "sql": syntax error
sql placeholder
near "sql": syntax error
sql placeholder
near "sql": syntax error
sql placeholder
near "sql": syntax error
100%|█████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:05<00:00,  5.33s/it]
2023-03-01 14:17:33,138 INFO root 输出结果
['sql placeholder']

这是用单例测试，用的32G V100

**Comment by lihaoyang-ruc** [comment]
这个问题由于不活跃而被关闭。如果你有进一步的问题，请随时再次打开它或创建一个新的问题。
