### ISSUE TITLE
Error in running Inference script

### ISSUE THREAD

**Issue by hmhm1190** [RUCKBReasoning/RESDSQL#30]
I am trying to run the inference script but getting **TypeError: expected str, bytes or os.PathLike object, not NoneType**

I am also attaching the entire output log.
[New Text Document (2).txt](https://github.com/RUCKBReasoning/RESDSQL/files/11721488/New.Text.Document.2.txt)

**Comment by lihaoyang-ruc** [comment]
Can you share your Python environment? Run `pip list` and `conda list`. I need to check if your environment is well configured.

**Comment by hmhm1190** [comment]
[Conda_env.txt](https://github.com/RUCKBReasoning/RESDSQL/files/11734598/Conda_env.txt)
[RESDSQL_env.txt](https://github.com/RUCKBReasoning/RESDSQL/files/11734599/RESDSQL_env.txt)

**Comment by lihaoyang-ruc** [comment]
> 



> Is it necessary to run the training script for inference?
> 
> I wanted to use the pre-trained model so i just downloaded T5-base model checkpoints and cross-encoder checkpoint. and copied them both into models folder.

no, you can directly run inference scripts after downloading T5 and cross-encoder checkpoints.

**Comment by hmhm1190** [comment]
> > 
> 
> > Is it necessary to run the training script for inference?
> > I wanted to use the pre-trained model so i just downloaded T5-base model checkpoints and cross-encoder checkpoint. and copied them both into models folder.
> 
> no, you can directly run inference scripts after downloading T5 and cross-encoder checkpoints.

Would you pls help me resolving the error: TypeError: expected str, bytes or os.PathLike object, not NoneType
[out_14June.txt](https://github.com/RUCKBReasoning/RESDSQL/files/11742154/out_14June.txt)

**Comment by lihaoyang-ruc** [comment]
It looks like the cross-encoder checkpoints are not downloading correctly, can you re-download and see if this issue still exists?

**Comment by lihaoyang-ruc** [comment]
By the way, you'd better create a new conda environment, because I updated requirements.txt yesterday.

**Comment by hmhm1190** [comment]
Oh okk Thanks !!!
