### ISSUE TITLE
inference cspider in 3b t5

### ISSUE THREAD

**Issue by EnHuiPug** [RUCKBReasoning/RESDSQL#32]
OSError: Error no file named pytorch_model.bin found in directory ./models/text2natsql-mt5-xl-cspider/checkpoint-167433 but there is a file for Flax weights. Use `from_flax=True` to load this model from those weights.

貌似是因为`transformers==4.17.0`不支持分片的模型（https://discuss.huggingface.co/t/flan-t5-xl-model-does-not-appear-to-have-a-file-named-pytorch-model-bin/30395）

**Comment by lihaoyang-ruc** [comment]
> OSError: Error no file named pytorch_model.bin found in directory ./models/text2natsql-mt5-xl-cspider/checkpoint-167433 but there is a file for Flax weights. Use `from_flax=True` to load this model from those weights.
> 
> 貌似是因为`transformers==4.17.0`不支持分片的模型（[https://discuss.huggingface.co/t/flan-t5-xl-model-does-not-appear-to-have-a-file-named-pytorch-model-bin/30395）](https://discuss.huggingface.co/t/flan-t5-xl-model-does-not-appear-to-have-a-file-named-pytorch-model-bin/30395%EF%BC%89)

感谢你的指正，我将在最新版本中修复这个问题。

**Comment by lihaoyang-ruc** [comment]
> > OSError: Error no file named pytorch_model.bin found in directory ./models/text2natsql-mt5-xl-cspider/checkpoint-167433 but there is a file for Flax weights. Use `from_flax=True` to load this model from those weights.
> > 貌似是因为`transformers==4.17.0`不支持分片的模型（[https://discuss.huggingface.co/t/flan-t5-xl-model-does-not-appear-to-have-a-file-named-pytorch-model-bin/30395）](https://discuss.huggingface.co/t/flan-t5-xl-model-does-not-appear-to-have-a-file-named-pytorch-model-bin/30395%EF%BC%89)
> 
> 感谢你的指正，我将在最新版本中修复这个问题。

已在requirements.txt中将transformers的版本指定为4.28.1，该版本支持加载分片模型。
