### ISSUE TITLE
Timestamp Functionality

### ISSUE THREAD

**Issue by PiranavS** [RUCKBReasoning/RESDSQL#33]
Hey, I would like to know what to do, to train the model with data so that it supports timestamps functionality as like in Druid SQL interface for example. Is there a way to do add timestamps functionality as well.

**Comment by PiranavS** [comment]
And is there a way to run single test case inference on the cross-encoder alone? How do I input a question and the corresponding columns and get the reduced input sequence to the decoder.

**Comment by lihaoyang-ruc** [comment]
> Hey, I would like to know what to do, to train the model with data so that it supports timestamps functionality as like in Druid SQL interface for example. Is there a way to do add timestamps functionality as well.

Maybe you have to train RESDSQL on your dataset with SQL queries that use the timestamp function. The checkpoints we released were trained on Spider and it only supports the following SQL keywords:  ['SELECT', 'FROM', 'WHERE', 'GROUP', 'ORDER', 'LIMIT', 'INTERSECT', 'UNION', 'EXCEPT', 'JOIN', 'ON', 'AS', 'NOT', 'BETWEEN', 'IN', 'LIKE', 'IS', 'EXISTS', 'MAX', 'MIN', 'COUNT', 'SUM', 'AVG', 'AND', 'OR', 'DESC', 'ASC'].

**Comment by lihaoyang-ruc** [comment]
> And is there a way to run single test case inference on the cross-encoder alone? How do I input a question and the corresponding columns and get the reduced input sequence to the decoder.

No, the input of the cross-encoder is a preprocessed dataset, so you should run `preprocessing.py` on your dataset before running the cross-encoder.

**Comment by PiranavS** [comment]
> > Hey, I would like to know what to do, to train the model with data so that it supports timestamps functionality as like in Druid SQL interface for example. Is there a way to do add timestamps functionality as well.
> 
> Maybe you have to train RESDSQL on your dataset with SQL queries that use the timestamp function. The checkpoints we released were trained on Spider and it only supports the following SQL keywords: ['SELECT', 'FROM', 'WHERE', 'GROUP', 'ORDER', 'LIMIT', 'INTERSECT', 'UNION', 'EXCEPT', 'JOIN', 'ON', 'AS', 'NOT', 'BETWEEN', 'IN', 'LIKE', 'IS', 'EXISTS', 'MAX', 'MIN', 'COUNT', 'SUM', 'AVG', 'AND', 'OR', 'DESC', 'ASC'].

To do training with your code, should I just add the functions in the sql keywords list in the preprocessing.py file or are there more changes that are needed to be done?
