### ISSUE TITLE
请问是否有计划对mT5模型的训练代码进行模型并行化改造？

### ISSUE THREAD

**Issue by Promise-Lv** [RUCKBReasoning/RESDSQL#38]
在复现mT5 text2sql的训练时，我们发现一张40G显存的GPU一个批次都跑不起来……

**Comment by lihaoyang-ruc** [comment]
不好意思，我们目前没有这样的计划。

作为一个学术研究项目，我们没有太多精力和时间来适应各种用户的要求。如果你能帮助我们实现，欢迎你提交 PR，我们将不胜感激。

感谢您的理解。

**Comment by lihaoyang-ruc** [comment]
感谢！ @Promise-Lv

**Comment by Promise-Lv** [comment]
数据并行相关的代码已提了PR~
