### ISSUE TITLE
NatSQL-Parser

### ISSUE THREAD

**Issue by NicolasB108** [RUCKBReasoning/RESDSQL#39]
Hey, 
I'm very interested in your work. I want to train RESDSQL+NatSQL on my own dataset. I had no problems to train only RESDSQL but I don't know how to create the NatSQL-JSON-file. Do you know if there is any script available for parsing SQL-queries into NatSQL?  
Thanks in advance!

**Comment by lihaoyang-ruc** [comment]
Sorry. I don't have the SQL-to-NatSQL script here either, the NatSQL datasets (only for Spider) used in this project are obtained from their GitHub (https://github.com/ygan/NatSQL). 

By the way, I also looked for the SQL-to-NatSQL code on their GitHub for a long time when I started this project, but finally, I determined that this part is not open source :(
