### ISSUE TITLE
请问在text2sql和schema_item_classifier中，精调的思路是全参精调？还是部分参数精调？

### ISSUE THREAD

**Issue by ManchesterWuer** [RUCKBReasoning/RESDSQL#40]
我学习了一下代码，似乎没有看到哪里写了freeze部分参数的规模。

**Comment by lihaoyang-ruc** [comment]
全参数微调

**Comment by ManchesterWuer** [comment]
mT5-XL (3.7 billion parameters)，全参精调，您是使用1张a100完成的？可能我对a100的能力有低估。
请问，一张a100卡+Cspider数据（大约1万条），大概训练多久？

**Comment by lihaoyang-ruc** [comment]
不好意思，我记不太清了，但是训练可以在两天内可以完成。但是除去训练的时间开销，我们还需要一些时间来评估中间的检查点。
