### ISSUE TITLE
How can I expose it as a API Service ?

### ISSUE THREAD

**Issue by vaib26** [RUCKBReasoning/RESDSQL#41]
Both the steps should be part of the service.

**Comment by lihaoyang-ruc** [comment]
Sorry, we don't have such a plan at the moment, but maybe we'll put this on the agenda later. I have currently rewritten the first phase (i.e., the cross-encoder) into a more lightweight module that is plug-and-play and I will open-source it in my future work.

Anyway, thanks for the suggestion!

**Comment by vaib26** [comment]
Please , we would really appreciate if you guys publish the code for hosting and serving soon. This will help in leveraging the RESDSQL Model capabilities.

Also if you are aiming for the same , are you planning to use fastapi framework for deployment?

**Comment by lihaoyang-ruc** [comment]
Our team members are currently devoting most of their efforts to our new work. 

We believe that RESDSQL will bring some inspiration and convenience to the industry. However, we need to emphasize that, as a purely academic research project, we do not have much time and energy to accommodate the various demands.

Thank you for your understanding.
