### ISSUE TITLE
SQL句中的value是如何确定的？

### ISSUE THREAD

**Issue by ManchesterWuer** [RUCKBReasoning/RESDSQL#46]
以spider、Cspider为例，一条生成的SQL语句，包含sql语法（骨架）、字段信息、值信息（value），比如：在”计算年龄大于50岁的男性人口”中，50就是值。
我的问题是，值是如何确定的？具体而言，从自然语言问句中分辨出哪些是值（比如，从“年龄大于50岁的男性人口”中，分辨出50是值），是模型通过训练获得的能力，还是spder、Cspider已经预先界定了哪些是值？如果是通过训练获得了分辨值的能力，能简单介绍一下思路吗？

**Comment by lihaoyang-ruc** [comment]
这部分我们做的比较简单，只是follow了前人的一项工作PICARD（https://github.com/ServiceNow/picard）。

具体来说，当来一个问题的时候，我们会根据问题和数据库中所有values进行一个字符串级别的相似度计算，抽取出相似度很高的values拼在对应列后面。当训练模型的时候，它就可以学到“列后面跟的values很可能是会出现在SQL中的值”。

但仔细思考，这样做其实是有若干问题的，比如它不能处理语义级别的相似度，因为目前只是根据字符串匹配相似度进行打分；其次，对于非常大的表（可能存了上百GB的数据），就算是简单的字符串匹配，也会消耗大量的时间；最后，在很多实际生产环境中，由于隐私问题，我们根本没有权限拿到数据库中的所有values。

**Comment by ManchesterWuer** [comment]
@lihaoyang-ruc 所以，选择值的前提，是直接读取了原始数据对吗？我一直以为，值的选择是通过学习自然语言问句分解出来的（因为值在自然语言问句中可能比较有特异性，而且经常是原封不动的“搬到”sql里，比如：数字）。那如果原始数据的量非常大，是不是可以认为“索引+匹配”的方式速度会比较慢？
如果希望能直接从自然语言问句中直接识别出值，您有推荐的方案吗？

**Comment by lihaoyang-ruc** [comment]
是这样的，模型在数据上训练后，其实是可以直接识别出问题中出现的值。SQL中的values一部分可以从问题中直接copy过来，另一部分可以从DB中按照字符串相似度抽出的values直接copy过来。

**Comment by ManchesterWuer** [comment]
您能帮忙举个例子吗？怎样的value，是不能从问题copy，而只能从DB中抽取的？
