### ISSUE TITLE
请问如果要自己准备dataset做训练或者测试，有什么格式要求吗？

### ISSUE THREAD

**Issue by dyc1998108** [RUCKBReasoning/RESDSQL#51]
请问如果要自己准备dataset，有什么格式要求吗？

**Comment by lihaoyang-ruc** [comment]
目前是需要的，因为我依赖database来采样生成没有语法错误的SQL，你可以在sqlite中创建空数据库，不插入任何数据，只当作语法检查器使用。又或者你可以自己实现一个语法检查器，替代掉去database中执行的步骤。

**Comment by dyc1998108** [comment]
好的，十分感谢，database执行步骤具体是在哪个文件呢？我看一下如何自己实现检查器替代？

**Comment by lihaoyang-ruc** [comment]
utils/text2sql_decoding_utils.py文件的`results = execute_sql(cursor, pred_sql)`行。
