### ISSUE TITLE
natsql是如何转换的？如何取骨架？

### ISSUE THREAD

**Issue by ManchesterWuer** [RUCKBReasoning/RESDSQL#54]
我注意到，作者在另一个问题里提到过，似乎是sql-to-natsql的代码没有开源，所以作者是直接使用了已经转换后的数据集吗？（Cspider也有现成的数据集？）
同时，skeleton-aware的decoder，前半部分是sql骨架，后半部分是sql，那对于natsql来说，是否可以理解为：前半部分是natsql骨架，后半部分是natsql？那么，natsql的骨架是怎么处理的呢？

**Comment by lihaoyang-ruc** [comment]
Q：“我注意到，作者在另一个问题里提到过，似乎是sql-to-natsql的代码没有开源，所以作者是直接使用了已经转换后的数据集吗？（Cspider也有现成的数据集？）”
A：是的，sql-to-natsql的代码并没有开源，我用的是转换后的现成数据集。关于CSpider，它是没有现成NatSQL，但是我观察到CSpider和Spider中SQL唯一的不同就是CSpider的values是中文，所以我直接在Spider的NatSQL上将它的values替换成中文，从而得到了CSpider的NatSQL数据集。

Q：“同时，skeleton-aware的decoder，前半部分是sql骨架，后半部分是sql，那对于natsql来说，是否可以理解为：前半部分是natsql骨架，后半部分是natsql？那么，natsql的骨架是怎么处理的呢？”
A：你的理解是对的。由于sql和natsql高度相似，因此抽取它们的骨架用的同一个函数。
