### ISSUE TITLE
Execuse me. What happened to paper CodeS? Isn't this article open source before?

### ISSUE THREAD

**Issue by kanseaveg** [RUCKBReasoning/RESDSQL#55]
![image](https://github.com/RUCKBReasoning/RESDSQL/assets/80022154/2d5ab380-76f6-4542-929a-ac67464ab1b7)

**Comment by lihaoyang-ruc** [comment]
Hello,

This paper is presently undergoing the peer review process. To maintain the integrity of the double-blind review system, we have temporarily concealed it. Please don't worry, both the paper and the associated project will be made publicly available and open-sourced once the review is complete. We appreciate your patience and encourage you to stay tuned for updates.

**Comment by kanseaveg** [comment]
ok. I'm look forawrd to.

**Comment by lihaoyang-ruc** [comment]
> ok. I'm looking forawrd to.

@kanseaveg

We will be open-sourcing a text2sql demo, which has been developed based on our CodeS model. To get a firsthand experience of its capabilities, you are warmly invited to try it out at: http://101.43.153.141:5000/chatbot

Please stay tuned, as we will be releasing the source code for the demo later this week.

**Comment by lihaoyang-ruc** [comment]
Thank you🤗

**Comment by kanseaveg** [comment]
![image](https://github.com/RUCKBReasoning/RESDSQL/assets/80022154/2498beaa-158a-45ee-a8cc-8f59f5b6583e)
good job! 
well down!

**Comment by lihaoyang-ruc** [comment]
@kanseaveg 
Hello! Our demo is readily available for access and exploration at https://github.com/RUCKBReasoning/text2sql-demo. We encourage you to utilize it in building your text-to-SQL applications. Please note that this work is completely open-source for academic purposes. Feel free to dive in!

**Comment by kanseaveg** [comment]
Good job, I'll give it a try🤗🤗🤗

**Comment by lihaoyang-ruc** [comment]
Given that CodeS primarily operates as an English language model, it might not capture the full range of common Chinese characters, leading to the tokenization of numerous Chinese characters as <UNKNOWN>.

To address this in our demo, we have integrated a translation tool to convert non-English user queries into English. 

While this approach might lack a certain elegance, it has demonstrated efficacy in our preliminary tests.
