### ISSUE TITLE
Question about evaluation scripts

### ISSUE THREAD

**Issue by nomalocaris** [RUCKBReasoning/RESDSQL#59]
I notice that you and other works (e.g. PICARD) use the following evaluation pkgs:
> git clone https://github.com/ElementAI/spider.git
> git clone https://github.com/ElementAI/test-suite-sql-eval.git

Those pkgs are different from the original version published by [taoyds](https://github.com/taoyds). 

Could you tell me what modifications they make and if those modifications have an impact on performance?

**Comment by lihaoyang-ruc** [comment]
Their primary modification involves encapsulating the evaluation script into a callable function, enabling convenient usage during model checkpoint evaluation. 

Furthermore, I confirmed that the outcomes from their revised version consistently align with those from the official version. 

To alleviate any lingering concerns, you might consider saving the model's output to a file and subsequently employing the official script for evaluation.

**Comment by nomalocaris** [comment]
> Their primary modification involves encapsulating the evaluation script into a callable function, enabling convenient usage during model checkpoint evaluation.
> 
> Furthermore, I confirmed that the outcomes from their revised version consistently align with those from the official version.
> 
> To alleviate any lingering concerns, you might consider saving the model's output to a file and subsequently employing the official script for evaluation.

Thanks for answering. Best wish.
