### ISSUE TITLE
请问推理方法

### ISSUE THREAD

**Issue by annanfree** [RUCKBReasoning/RESDSQL#60]
你好，我刚开始了解这个项目。请问有没有简单直接的推理函数，不在spider上推理。就是自己指定自己特有的数据库ddl，然后给出问题，模型输出sql，不需要执行sql验证。

**Comment by lihaoyang-ruc** [comment]
抱歉，目前RESDSQL不支持这样的推理方式。如果想在自己的数据库上推理，我建议您使用我们最新的Demo项目：https://github.com/RUCKBReasoning/text2sql-demo。尽管如此，这个Demo也需要您根据您的DDL在SQLite中创建一个空数据库才能正常进行推理。

**Comment by lihaoyang-ruc** [comment]
This issue is being closed due to a lack of activity. However, if you continue to encounter problems and need further assistance, please don't hesitate to reopen it, and we will be more than happy to help with additional troubleshooting.
