### ISSUE TITLE
部分带有别名的sql在经过normalization处理后出现错误

### ISSUE THREAD

**Issue by riddiculous** [RUCKBReasoning/RESDSQL#64]
当前的normalization方法只能正确处理表名和别名一一对应的情况。对于一个别名对应多个表，或者多个别名对应一个表的情况，normalization后出现错误。以dev集数据举例：

1. Show name of all students who have some friends and also are liked by someone else.
处理前：
SELECT T2.name FROM Friend AS T1 JOIN Highschooler AS T2 ON T1.student_id  =  T2.id INTERSECT SELECT T2.name FROM Likes AS T1 JOIN Highschooler AS T2 ON T1.liked_id  =  T2.id
处理后：
select highschooler.name from friend join highschooler on **likes.student_id** = highschooler.id intersect select highschooler.name from likes join highschooler on likes.liked_id = highschooler.id
正确结果应为：
select highschooler.name from friend join highschooler on **friend.student_id** = highschooler.id intersect select highschooler.name from likes join highschooler on likes.liked_id = highschooler.id
由于intersect前后两个子句的T1对应不同的表（Friend和Likes），当前方法无法识别这种情况。

2. How many flights depart from City 'Aberdeen' and have destination City 'Ashley'?
处理前：
SELECT count(*) FROM FLIGHTS AS T1 JOIN AIRPORTS AS T2 ON T1.DestAirport  =  T2.AirportCode JOIN AIRPORTS AS T3 ON T1.SourceAirport  =  T3.AirportCode WHERE **T2.City  =  "Ashley" AND T3.City  =  "Aberdeen"**
处理后：
select count ( * ) from flights join airports on flights.destairport = airports.airportcode join airports on flights.sourceairport = airports.airportcode where **airports.city = 'Ashley' and airports.city = 'Aberdeen'** 运行报错：ambiguous column name: airports.city
T2和T3都对应AIRPORTS表，但join的条件不同，可以看作不同的子表，因此where的两个条件不冲突，normalization之后，T2和T3被替换为同一个表，where冲突报错。

**Comment by lihaoyang-ruc** [comment]
这个情况的确存在，因为我处理table alias的时候，按照字符串匹配来做的，并没有考虑具体的AST。不过我当时在Spider的train和dev上有检查，normalization之后报错的SQL查询非常少。

如果您觉得这个问题对您很重要，我有两个建议：（1）从SQL AST角度重写remove_table_alias函数；（2）不处理table alias（把remove_table_alias函数去掉），因为通过大量训练，seq2seq模型其实也可以学到table alias的对应关系。

**Comment by riddiculous** [comment]
> 这个情况的确存在，因为我处理table alias的时候，按照字符串匹配来做的，并没有考虑具体的AST。不过我当时在Spider的train和dev上有检查，normalization之后报错的SQL查询非常少。
> 
> 如果您觉得这个问题对您很重要，我有两个建议：（1）从SQL AST角度重写remove_table_alias函数；（2）不处理table alias（把remove_table_alias函数去掉），因为通过大量训练，seq2seq模型其实也可以学到table alias的对应关系。

谢谢您的回复！
