### ISSUE TITLE
Inference script not working

### ISSUE THREAD

**Issue by Saivignesh-05** [RUCKBReasoning/RESDSQL#65]
I'm running currently in Google colab with latest version of all packages
I'm trying to run the inference script "infer_text2natsql.sh". Im encountering an error which goes like
Traceback (most recent call last):
  File "/content/RESDSQL/schema_item_classifier.py", line 465, in <module>
    total_table_pred_probs, total_column_pred_probs = _test(opt)
  File "/content/RESDSQL/schema_item_classifier.py", line 407, in _test
    model.load_state_dict(torch.load(opt.save_path + "/dense_classifier.pt", map_location=torch.device('cpu')))
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 2152, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for MyClassifier:
	Unexpected key(s) in state_dict: "plm_encoder.embeddings.position_ids".

I tried printing the model def:
MyClassifier(
  (plm_encoder): RobertaModel(
    (embeddings): RobertaEmbeddings(
      (word_embeddings): Embedding(50266, 1024, padding_idx=1)
      (position_embeddings): Embedding(514, 1024, padding_idx=1)
      (token_type_embeddings): Embedding(1, 1024)
      (LayerNorm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): RobertaEncoder(
      (layer): ModuleList(
        (0-23): 24 x RobertaLayer(
          (attention): RobertaAttention(
            (self): RobertaSelfAttention(
              (query): Linear(in_features=1024, out_features=1024, bias=True)
              (key): Linear(in_features=1024, out_features=1024, bias=True)
              (value): Linear(in_features=1024, out_features=1024, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): RobertaSelfOutput(
              (dense): Linear(in_features=1024, out_features=1024, bias=True)
              (LayerNorm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
          )
          (intermediate): RobertaIntermediate(
            (dense): Linear(in_features=1024, out_features=4096, bias=True)
            (intermediate_act_fn): GELUActivation()
          )
          (output): RobertaOutput(
            (dense): Linear(in_features=4096, out_features=1024, bias=True)
            (LayerNorm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
    (pooler): RobertaPooler(
      (dense): Linear(in_features=1024, out_features=1024, bias=True)
      (activation): Tanh()
    )
  )
  (column_info_cls_head_linear1): Linear(in_features=1024, out_features=256, bias=True)
  (column_info_cls_head_linear2): Linear(in_features=256, out_features=2, bias=True)
  (column_info_bilstm): LSTM(1024, 512, num_layers=2, bidirectional=True)
  (column_info_linear_after_pooling): Linear(in_features=1024, out_features=1024, bias=True)
  (table_name_cls_head_linear1): Linear(in_features=1024, out_features=256, bias=True)
  (table_name_cls_head_linear2): Linear(in_features=256, out_features=2, bias=True)
  (table_name_bilstm): LSTM(1024, 512, num_layers=2, bidirectional=True)
  (table_name_linear_after_pooling): Linear(in_features=1024, out_features=1024, bias=True)
  (leakyrelu): LeakyReLU(negative_slope=0.01)
  (tanh): Tanh()
  (table_column_cross_attention_layer): MultiheadAttention(
    (out_proj): NonDynamicallyQuantizableLinear(in_features=1024, out_features=1024, bias=True)
  )
  (dropout): Dropout(p=0.2, inplace=False)
)

Can sm1 please help me here

**Comment by lihaoyang-ruc** [comment]
It appears that the error originates from the line `model.load_state_dict(torch.load(opt.save_path + "/dense_classifier.pt", map_location=torch.device('cpu')))`.

Could you try modifying it to `model.load_state_dict(torch.load(opt.save_path + "/dense_classifier.pt", map_location=torch.device('cpu')), strict=False)`?

I suspect the issue may stem from using the latest versions of all packages. To prevent further complications, I recommend adhering to the specific package versions listed in our [requirements.txt](https://github.com/RUCKBReasoning/RESDSQL/blob/main/requirements.txt).

**Comment by lihaoyang-ruc** [comment]
In the version 4.28.1 of the Transformers library, which we are using in this repo, the `position_ids` within `RobertaEmbeddings` are registered with `persistent=True` by default in the `register_buffer` function:

```python
self.register_buffer("position_ids", torch.arange(config.max_position_embeddings).expand((1, -1)))
```

This means that `position_ids` will be included in the model's checkpoints, similar to standard parameters.

However, in the latest version of the `transformers` library, there has been a change to this line:

```python
self.register_buffer(
    "position_ids", torch.arange(config.max_position_embeddings).expand((1, -1)), persistent=False
)
```

By setting `persistent=False`, the latest version no longer requires the loading of `plm_encoder.embeddings.position_ids` from the checkpoint. This modification is the source of the issue we're encountering.

**Comment by Saivignesh-05** [comment]
The code seems to be running for now (item_classifier_step). I'm impressed that you replied so early. Thanks for the reply.

**Comment by Saivignesh-05** [comment]
The issue is solved. Thank you so much

**Comment by lihaoyang-ruc** [comment]
> The issue is solved. Thank you so much. Can you please update the requirements.txt with these packages. These were missing when I ran the code rapidfuzz sql_metadata tqdm transformers argparse scikit-learn tensorboard func-timeout

Thank you for your suggestion. I have updated it accordingly.
