### ISSUE TITLE
CoSQL

### ISSUE THREAD

**Issue by Saivignesh-05** [RUCKBReasoning/RESDSQL#66]
Hey @lihaoyang-ruc 
I know you would be familiar with the CoSQL dataset. Can we train RESDSQL for CoSQL dataset. What are the changes that need to be made to suit according to the data.

**Comment by lihaoyang-ruc** [comment]
Hello! Apologies for the delay; I've just returned from vacation. The matter you've mentioned bears resemblance to a discussion found at https://github.com/RUCKBReasoning/RESDSQL/issues/58.
