### ISSUE TITLE
关于RESDSQL在BIRD上的运行时间

### ISSUE THREAD

**Issue by Yhw109** [RUCKBReasoning/RESDSQL#68]
您好，我想在BIRD上运行RESDSQL并查看test_with_probs.json的结果。我选择了运行sh scripts/inference/infer_text2sql.sh base spider，（spider文件夹的内容修改为了BIRD）但是我发现在BIRD上运行preprocessing.py会花费很久的时间，每个iteration需要3分钟以上。我想询问一下有没有提速的方法，还是是因为我的运行过程有问题。感谢。
![微信截图_20240311112419](https://github.com/RUCKBReasoning/RESDSQL/assets/61622924/ce47a6aa-7388-479a-a5c0-8b01de270d67)

**Comment by lihaoyang-ruc** [comment]
这是正常的，在BIRD上预处理运行时间长是因为在BIRD基准中有一些数据库存的values非常多。

在预处理的过程中，每个问题都需要和数据库中存的每个value进行字符串相似度的对比，以从数据库中抽取出问题可能涉及的values。然而，当values非常多的时候，这个过程就会及其缓慢。

为了解决这个问题，我们最近的工作CodeS（[paper](https://arxiv.org/abs/2402.16347), [code](https://github.com/RUCKBReasoning/codes)）引入了一个“粗粒度到细粒度”的value抽取方案。通过对values提前建索引来加速这个过程。

如果您只是想在RESDSQL上跑通BIRD，我建议您直接把preprocess.py中的这行代码 [link](https://github.com/RUCKBReasoning/RESDSQL/blob/cf4ca667fdeb1622d8a412567f51d0fc411113f3/preprocessing.py#L354)直接替换成一个空列表`db_contents=[]`即可。

如果您在找在BIRD基准上上更强大的开源模型，不妨尝试下我们新工作CodeS。

**Comment by Yhw109** [comment]
感谢您详细的解答！我会仔细阅读CodeS的论文。
