### ISSUE TITLE
你好，请问如何SQL2NatSQL？我想用自己的数据集跑text2NatSQL的方法。

### ISSUE THREAD

**Issue by yicun0720** [RUCKBReasoning/RESDSQL#74]
比如：
NatSQL/NatSQLv1_6/train_spider-natsql.json
NatSQL/NatSQLv1_6/dev-natsql.json

这种文件是怎么生成的呢？

**Comment by lihaoyang-ruc** [comment]
请参考已有issue的讨论：https://github.com/RUCKBReasoning/RESDSQL/issues/39#issuecomment-1611015614

目前来看NatSQL并没有开源这一部分。NatSQL/NatSQLv1_6/train_spider-natsql.json和NatSQL/NatSQLv1_6/dev-natsql.json是它放在Github里的文件，我直接拿来使用了。

**Comment by yicun0720** [comment]
感谢！
