### ISSUE TITLE
How I can do inference on the model only with a question?

### ISSUE THREAD

**Issue by starkf013** [RUCKBReasoning/RESDSQL#8]
Hi, I want to know if is possible to use the model to get directly the SQL statment, after giving it a question in natural language. Actually if for example, I use the dev.json (modified version from spider dataset) attached, I have no result in pred.sql.
Thank you for help.
![Screenshot 2023-03-16 111012](https://user-images.githubusercontent.com/128039537/225585077-19796005-dc45-4446-aa15-341dbb8515fd.png)

**Comment by starkf013** [comment]
I can give it also the database schema, but in the dev.json for example, there is also the query, that is a result that I want. It's possible to give question + database schema but without the query?

**Comment by nkezhaya** [comment]
@lihaoyang-ruc I'm trying to add a dataset to the `database/` folder to and create custom questions for this, separate from the spider datasets. Is there a way to easily create `tables.json` and the other JSON files needed for `RESDSQL` to run inference, or do these JSON files need to be crafted by hand?

**Comment by lihaoyang-ruc** [comment]
I am sorry for this. I don't have such a script to create the `tables.json` file, because all datasets adopted in RESDSQL (such as Spider-DK, Dr.Spider, etc.) already obey the same structure as Spider. Maybe you can find something useful from Spider's project (https://github.com/taoyds/spider).

**Comment by lihaoyang-ruc** [comment]
This question is closed due to inactivity. If you have further questions, please feel free to open it again or create a new question.

**Comment by mellahysf** [comment]
@lihaoyang-ruc Can you please provide a script that takes as inputs "Database + Question" and returns the corresponding SQL query?
