### ISSUE TITLE
schema_item_classifier.py如何对新增库中的表名和列名进行预测

### ISSUE THREAD

**Issue by 694344851** [RUCKBReasoning/RESDSQL#9]
schema_item_classifier.py  是一个选表选列的模型，如何对一个新增的库中的表和列进行选取，预先并不知道新增苦衷有多少表和列数据

**Comment by lihaoyang-ruc** [comment]
我没有太理解您的意思，但我们的schema item ranker可以处理数据库中包含任意数量的表和列的情况。

**Comment by 694344851** [comment]
生成的sql里面有时候回出现@。@  这个是在哪一步进行处理的

**Comment by lihaoyang-ruc** [comment]
`@.@`是NatSQL中定义的特殊符号，详见论文https://arxiv.org/abs/2109.05153。在utils/text2sql_decoding_utils.py中使用natsql_to_sql函数处理。

**Comment by lihaoyang-ruc** [comment]
This question is closed due to inactivity. If you have further questions, please feel free to open it again or create a new question.
